### ISSUE TITLE
Proxy configuration for npm

### ISSUE THREAD

**Issue by jochenehret** [CloudCredo/graphite-statsd-boshrelease#2]
Hi,

I had an issue when deploying 0.0.1 which took me some time to resolve. The packages/statsd/packaging script contains an "npm install" call which doesn't work if you're behind a proxy. I fixed it by adding

```
npm config set proxy http://proxy:8080
npm config set https-proxy http://proxy:8080
npm install
```

I've seen that the "npm install" call has been removed in the meanwhile. Will this be still an issue in the next release 0.0.2? If yes, could you add a short note or an option to configure a proxy?

Thanks and Best Regards,

  Jochen.

**Comment by teddyking** [comment]
Hi Jochen,

Yes the `npm install` call has been removed from the packaging script. There's some further context around this [here](https://github.com/CloudCredo/graphite-statsd-boshrelease/issues/1). 

This shouldn't be an issue in the next release and you should be able to deploy now from the master branch without needing to make any npm/proxy fixes.

Thanks!
Ed

**Comment by teddyking** [comment]
I'm going to close this one off, but please let me know if you'd like any further info.

Thanks!
